# Generated by Django 5.1.4 on 2025-01-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_remove_user_role_user__role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='_role',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest', 'Guest'), ('host', 'Host'), ('admin', 'Admin')], default='guest', max_length=5),
        ),
    ]
