# Generated by Django 5.1.4 on 2024-12-19 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=models.CharField(default=None, max_length=100), max_length=200),
        ),
    ]
