# Generated by Django 5.1.4 on 2024-12-19 14:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_message_conversation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='participants_id',
        ),
        migrations.AddField(
            model_name='conversation',
            name='participants_id',
            field=models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
