# Generated by Django 5.1.4 on 2024-12-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_alter_message_conversation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(max_length=100),
        ),
    ]
