pipeline {
    agent any

    stages {
        stage("Pull code from GitHub") {
            steps {
                git branch: 'main',
                    credentialsId: 'GitHub_Cred',
                    url: 'https://github.com/lawalgodwin/alx-backend-python'
            }
        }
        stage("install dependencies") {
            steps {
                dir('messaging_app') {
                    sh '''
                        rm -rf venv
                        python3 -m venv venv
                        bash -c "source venv/bin/activate"
                        venv/bin/pip3 install --upgrade pip
                        bash -c "apt install python3-dev default-libmysqlclient-dev build-essential pkg-config -y"
                        venv/bin/pip3 install -r messaging_app/requirements.txt
                    '''
                }
            }
        }
        stage("Test") {
            steps {
                dir("messaging_app") {
                    sh '''
                        bash -c "source venv/bin/activate"
                        venv/bin/pytest
                    '''
                }
            }
        }
    }
    
    post {
        always {
            dir("messaging_app") {
                sh '''
                    bash -c "source venv/bin/activate"
                    venv/bin/pytest --cov
                '''
            }
        }
    }
}