pipeline {
    agent any

    stages {
        stage("Pull code from GitHub") {
            steps {
                sh 'python3 -m venv venv && cd venv && chmod +x bin/activate && ./bin/activate'
                git branch: 'main', credentialsId: 'GitHub_Cred', url: 'https://github.com/lawalgodwin/alx-backend-python.git'
            }
        }
        stage("install dependencies") {
            steps {
                sh 'cd messaging_app && ls -l && python3 -m pip install django'
                // sh 'cd messaging_app && ls -l && python3 -m pip install -r requirements.txt'
            }
        }
        stage("Test") {
            steps {
                sh 'pytest'
            }
        }
    }
    
    post {
        always {
            echo 'pytest --cov'
        }
    }
}