
# Expose the messaging-app pod via service
---
apiVersion: v1
kind: Service
metadata:
  name: messaging-app-service
spec:
  selector:
    app: messaging-app
    tier: backend
    version: blue
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000