#!/usr/bin/env bash

# Install Kubernetes and Set Up a Local Cluster

# install minikube if not installed
if ! command -v minikube; then
    curl -LO https://github.com/kubernetes/minikube/releases/latest/download/minikube-linux-amd64
    sudo install minikube-linux-amd64 /usr/local/bin/minikube && rm minikube-linux-amd64
fi

# point kubectl to the minikube-installed version
alias kubectl=minikube kubectl

# start the local cluster
minikube start

# verifies that the cluster is running
kubectl cluster-info

# Retrieves the available pods from all namespaces
echo ".............PODS in the cluster............"
kubectl get pods -A

echo "....done...."
