name: Messaging app CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12.3]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        cd messaging_app && python3 -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests'
      env:
        DJANGO_SECRET_KEY: 69tgugtg%^fgJO&*&
        MYSQL_DB: mydb
        MYSQL_USER: userdb
        MYSQL_PASSWORD: password
        MYSQL_DB_HOST: localhost
        MYSQL_DB_PORT: 3306
        DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1,[::1],*
        DJANGO_DEBUG: False
      run: |
        echo "done"